http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  user:
    host: localhost
    paths: '/user/*'
  auth:
    host: localhost
    paths: '/auth/*'
  song:
    host: localhost
    paths: '/songs/*'
  artist:
    host: localhost
    paths: '/artist/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url: 'http://localhost:3002'
  authService:
    url: 'http://localhost:3001'
  songService:
    url: 'http://localhost:3003'
  artistService:
    url: 'http://localhost:3004'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  songPipeline:
    apiEndpoints:
      - song
    policies:
      - proxy:
          - action:
              serviceEndpoint: songService
              changeOrigin: true
  artistPipeline:
    apiEndpoints:
      - artist
    policies:
      - proxy:
          - action:
              serviceEndpoint: artistService
              changeOrigin: true
